version: '3.8'
    
networks:
  youtube-newsletter-network:
    driver: bridge

services:
  youtube-manager-api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:80'
    networks:
      - youtube-newsletter-network