networks:
  youtube-newsletter-network:
    driver: bridge

services:
  whisper-api:
    build: 
      context: ./whisper_api
      dockerfile: whisper.dockerfile
    ports:
      - '8000:80'
    networks:
      - youtube-newsletter-network

  youtube-manager-api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:80'
    networks:
      - youtube-newsletter-network